In [1]:
!pip install pyreadstat

Requirement already satisfied: pyreadstat in /opt/python/lib/python3.13/site-packages (1.3.2)
Requirement already satisfied: narwhals>=2.0 in /opt/python/lib/python3.13/site-packages (from pyreadstat) (2.12.0)
Requirement already satisfied: numpy in /opt/python/lib/python3.13/site-packages (from pyreadstat) (2.3.5)

In [2]:
import s3fs
import pandas as pd
import tempfile
fs = s3fs.S3FileSystem(client_kwargs={"endpoint_url": "https://minio.lab.sspcloud.fr"})

MY_BUCKET = "gbern13"

FILE_PATH_S3 = f"{MY_BUCKET}/diffusion/PISA2022/student_questionnaire/CY08MSP_STU_QQQ.SAV"
with fs.open(FILE_PATH_S3, "rb") as s3f:
    with tempfile.NamedTemporaryFile(suffix=".sav") as tmp:
        tmp.write(s3f.read())
        tmp.flush()
        df = pd.read_spss(tmp.name)

print(df.head())

       CNT  CNTRYID  CNTSCHID  CNTSTUID   CYC   NatCen  \
0  Albania  Albania  800282.0  800001.0  08MS  Albania
1  Albania  Albania  800115.0  800002.0  08MS  Albania
2  Albania  Albania  800242.0  800003.0  08MS  Albania
3  Albania  Albania  800245.0  800005.0  08MS  Albania
4  Albania  Albania  800285.0  800006.0  08MS  Albania

                                     STRATUM SUBNATIO   REGION OECD  ...  \
0  ALB - stratum 03: Urban / Center / Public  Albania  Albania   No  ...
1  ALB - stratum 03: Urban / Center / Public  Albania  Albania   No  ...
2   ALB - stratum 01: Urban / North / Public  Albania  Albania   No  ...
3  ALB - stratum 08: Rural / Center / Public  Albania  Albania   No  ...
4  ALB - stratum 03: Urban / Center / Public  Albania  Albania   No  ...

   PV3MPRE  PV4MPRE  PV5MPRE  PV6MPRE  PV7MPRE  PV8MPRE  PV9MPRE PV10MPRE  \
0  226.250  203.029  219.817  331.017  223.752  305.671  230.156  289.436
1  298.644  321.405  320.452  284.836  364.565  304.044  347.626  352.269
2  383.340  376.019  285.901  289.896  338.469  316.296  324.361  343.351
3  264.532  303.422  327.793  165.575  246.156  238.322  275.860  227.466
4  399.300  514.739  539.850  461.793  514.465  510.462  490.537  503.793

     SENWT             VER_DAT
0  0.55561    03MAY23:10:11:25
1  0.76431    03MAY23:10:11:25
2  1.37877    03MAY23:10:11:25
3  1.49361    03MAY23:10:11:26
4  0.65249    03MAY23:10:11:26

[5 rows x 1278 columns]

In [3]:
df

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,PV3MPRE,PV4MPRE,PV5MPRE,PV6MPRE,PV7MPRE,PV8MPRE,PV9MPRE,PV10MPRE,SENWT,VER_DAT
0,Albania,Albania,800282.0,800001.0,08MS,Albania,ALB - stratum 03: Urban / Center / Public,Albania,Albania,No,...,226.250,203.029,219.817,331.017,223.752,305.671,230.156,289.436,0.55561,03MAY23:10:11:25
1,Albania,Albania,800115.0,800002.0,08MS,Albania,ALB - stratum 03: Urban / Center / Public,Albania,Albania,No,...,298.644,321.405,320.452,284.836,364.565,304.044,347.626,352.269,0.76431,03MAY23:10:11:25
2,Albania,Albania,800242.0,800003.0,08MS,Albania,ALB - stratum 01: Urban / North / Public,Albania,Albania,No,...,383.340,376.019,285.901,289.896,338.469,316.296,324.361,343.351,1.37877,03MAY23:10:11:25
3,Albania,Albania,800245.0,800005.0,08MS,Albania,ALB - stratum 08: Rural / Center / Public,Albania,Albania,No,...,264.532,303.422,327.793,165.575,246.156,238.322,275.860,227.466,1.49361,03MAY23:10:11:26
4,Albania,Albania,800285.0,800006.0,08MS,Albania,ALB - stratum 03: Urban / Center / Public,Albania,Albania,No,...,399.300,514.739,539.850,461.793,514.465,510.462,490.537,503.793,0.65249,03MAY23:10:11:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613739,Uzbekistan,Uzbekistan,86000120.0,86007488.0,08MS,Uzbekistan,UZB - stratum 26: Khorezm/Rural,Uzbekistan,Uzbekistan,No,...,334.153,306.551,271.135,386.969,376.271,368.287,395.329,278.263,0.71987,02MAY23:13:18:15
613740,Uzbekistan,Uzbekistan,86000140.0,86007489.0,08MS,Uzbekistan,UZB - stratum 04: Andijan/Rural,Uzbekistan,Uzbekistan,No,...,272.456,335.952,232.583,179.328,233.470,203.001,254.340,233.187,0.65541,02MAY23:13:18:13
613741,Uzbekistan,Uzbekistan,86000024.0,86007490.0,08MS,Uzbekistan,UZB - stratum 10: Kashkadarya/Rural,Uzbekistan,Uzbekistan,No,...,395.368,451.614,432.586,387.329,456.236,424.790,408.986,460.542,0.67910,02MAY23:13:18:13
613742,Uzbekistan,Uzbekistan,86000174.0,86007491.0,08MS,Uzbekistan,UZB - stratum 16: Samarkand/Rural,Uzbekistan,Uzbekistan,No,...,339.529,272.346,317.838,248.165,405.860,364.173,346.663,341.668,0.68618,02MAY23:13:18:14
613743,Uzbekistan,Uzbekistan,86000123.0,86007492.0,08MS,Uzbekistan,UZB - stratum 10: Kashkadarya/Rural,Uzbekistan,Uzbekistan,No,...,384.307,416.631,337.422,370.817,395.176,412.317,390.490,439.211,0.67910,02MAY23:13:18:13

In [34]:
# On ne conserve que les observations associées à des élèves ayant à la fois
# répondu aux questionnaire sur la créativité (Option_CT), sur le bien-être (Option_WBQ)
# et dont les parents ont répondu au questionnaire (Option_PQ)

df_light=df[(df['Option_CT']=='Yes') & (df['Option_WBQ']=='Yes') & (df['Option_PQ']=='Yes')].copy()

In [35]:
s=pd.Series(df.columns)
s

0            CNT
1        CNTRYID
2       CNTSCHID
3       CNTSTUID
4            CYC
          ...
1273     PV8MPRE
1274     PV9MPRE
1275    PV10MPRE
1276       SENWT
1277     VER_DAT
Length: 1278, dtype: object

In [36]:
## Dataset réduit à considérer à partir de maintenant
variables=list(s[s.str.startswith("ST") | s.str.startswith("PA") | s.str.startswith("CREAT")])
data=df_light[variables].copy()
data

,STRATUM,ST001D01T,ST003D02T,ST003D03T,ST004D01T,ST250Q01JA,ST250Q02JA,ST250Q03JA,ST250Q04JA,ST250Q05JA,...,CREATOP,PAREDINT,STUBMI,PARINVOL,PASCHPOL,PAREXPT,CREATHME,CREATACT,CREATOPN,CREATOR
53834,BRA - stratum 06: Nordeste / Public State,Grade 10,September,2006,Male,Yes,No,No,Yes,Yes,...,0.3754,16.0,NaN,0.6663,1.7833,ISCED Level 3.4,-0.0013,2.0991,-0.2901,-0.9433
53835,BRA - stratum 10: Sul / Public State,Grade 10,December,2006,Female,Yes,No,Yes,Yes,Yes,...,-0.3146,12.0,18.37,0.1212,1.2997,ISCED Level 8,-0.9023,NaN,1.0647,2.8672
53836,BRA - stratum 02: Norte / Public State,Grade 10,July,2006,Female,Yes,Yes,Yes,Yes,Yes,...,-0.5333,16.0,18.82,-0.2988,-0.2559,ISCED Level 8,-0.3099,-0.9143,-0.3803,-0.2370
53837,BRA - stratum 14: Sudeste / Public State,Grade 10,July,2006,Female,Yes,Yes,Yes,Yes,Yes,...,-1.2665,16.0,20.31,0.6746,0.1974,ISCED Level 8,-3.6273,NaN,-1.2792,-1.1547
53838,BRA - stratum 14: Sudeste / Public State,Grade 9,July,2006,Female,Yes,No,No,Yes,Yes,...,2.6206,14.5,25.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456140,SAU - stratum 25: International/Male/West,Grade 10,February,2006,Male,No,Yes,Yes,Yes,Yes,...,2.4234,16.0,23.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456141,SAU - stratum 27: International/Female/Middle,Grade 10,August,2006,Female,No,Yes,Yes,Yes,Yes,...,2.3850,16.0,20.55,-0.3039,-1.4734,ISCED Level 6,-0.9465,NaN,0.1770,0.2288
456142,SAU - stratum 05: Public/Male/West,Grade 10,October,2006,Male,Yes,Yes,Yes,Yes,Yes,...,0.4710,16.0,18.82,1.4023,0.7065,ISCED level 7,-1.3226,NaN,-0.3228,0.0813
456143,SAU - stratum 02: Public/Male/Middle,Grade 11,February,2006,Male,Yes,Yes,No,Yes,Yes,...,0.3946,16.0,29.67,-0.0630,0.0414,ISCED Level 8,1.0115,1.2775,1.8537,1.1310
456144,SAU - stratum 05: Public/Male/West,Grade 10,July,2006,Male,No,No,No,Yes,Yes,...,-2.6635,16.0,17.17,0.7922,1.2897,ISCED Level 8,3.0723,3.0457,1.0256,1.3339

# **Construction des Variables**

### **Variables explicatives**

#### **Variables du ST questionnaire**

La variable *home*

Cette variable prend en compte le confort à la maison comme la présence ou non d'une chambre personnelle mais également l'accès ou non à des moyens de transport personnels (voiture, moto etc.). Cette variable ne prend pas en compte l'accès à la culture ni à des outils digitaux. 

Cette variable prend ses valeurs de 0 à 5

In [37]:
home_liste=['ST250Q01JA']+['ST251Q0'+str(i)+'JA' for i in range(1,5)]
df_home=data[home_liste].copy()
df_home

       ST250Q01JA ST251Q01JA ST251Q02JA     ST251Q03JA ST251Q04JA
53834         Yes       None       None            One        One
53835         Yes        Two       None            Two        Two
53836         Yes        One       None            Two        Two
53837         Yes        Two       None           None       None
53838         Yes       None        One           None        One
...           ...        ...        ...            ...        ...
456140         No        One       None            One        Two
456141         No        One       None            Two        Two
456142        Yes        Two       None  Three or more        Two
456143        Yes       None        One           None        One
456144         No       None       None           None        One

[38674 rows x 5 columns]

La variable *digital_devices*

Cette variable prend en compte l'accessibilité à des outils digitaux comme des tablettes, des logiciels ou applications éducatives mais aussi l'accessibilité à un réseau internet. 

Cette variable prend ses valeurs de 0 à 4

In [38]:
digital_liste=['ST250Q0'+str(i)+'JA' for i in range(2,6)]
df_digital=data[digital_liste].copy()
df_digital

       ST250Q02JA ST250Q03JA ST250Q04JA ST250Q05JA
53834          No         No        Yes        Yes
53835          No        Yes        Yes        Yes
53836         Yes        Yes        Yes        Yes
53837         Yes        Yes        Yes        Yes
53838          No         No        Yes        Yes
...           ...        ...        ...        ...
456140        Yes        Yes        Yes        Yes
456141        Yes        Yes        Yes        Yes
456142        Yes        Yes        Yes        Yes
456143        Yes         No        Yes        Yes
456144         No         No        Yes        Yes

[38674 rows x 4 columns]

La variable *culture*

Cette variable prend en compte l'accès à la culture en considérant notamment la présence ou non d'instruments de musique, d'oeuvres d'arts ou encore de livres. 

Cette variable prend ses valeurs de 0 à 3

In [39]:
culture_liste=['ST251Q06JA','ST251Q07JA']
df_culture=data[culture_liste].copy()
df_culture

       ST251Q06JA     ST251Q07JA
53834        None            One
53835        None            One
53836        None            One
53837        None           None
53838         One           None
...           ...            ...
456140       None            Two
456141       None  Three or more
456142       None           None
456143       None           None
456144       None           None

[38674 rows x 2 columns]

La variable *book*

Cette variable considère le nombre de livres présents à la maison. 

Cette variable prend ses valeurs de 0 à 6.

In [40]:
book_liste=['ST255Q01JA']
df_book=data[book_liste].copy()
df_book

                 ST255Q01JA
53834            1-10 books
53835           11-25 books
53836           11-25 books
53837   There are no books.
53838            1-10 books
...                     ...
456140        101-200 books
456141          11-25 books
456142          11-25 books
456143           1-10 books
456144  There are no books.

[38674 rows x 1 columns]

La variable *siblings*

Cette variable prend en compte le nombre de frères et soeurs au sein du foyer de l'élève. 

Cette variable prend ses valeurs de 0 à 3.

In [41]:
siblings_liste=['ST230Q01JA']
df_siblings=data[siblings_liste].copy()
df_siblings

           ST230Q01JA
53834             Two
53835   Three or more
53836   Three or more
53837   Three or more
53838   Three or more
...               ...
456140            Two
456141            One
456142  Three or more
456143  Three or more
456144  Three or more

[38674 rows x 1 columns]

La variable *parents*

Cette variable prend en compte le niveau d'étude et de qualification des deux parents.

Cette variable prend ses valeurs de 0 à 8.

In [42]:
parents_liste=['ST005Q01JA','ST007Q01JA']+['ST006Q0'+str(i)+'JA' for i in range(1,6)]+['ST008Q0'+str(i)+'JA' for i in range(1,6)]
df_parents=data[parents_liste].copy()
df_parents

,ST005Q01JA,ST007Q01JA,ST006Q01JA,ST006Q02JA,ST006Q03JA,ST006Q04JA,ST006Q05JA,ST008Q01JA,ST008Q02JA,ST008Q03JA,ST008Q04JA,ST008Q05JA
53834,<ISCED level 3.4>,<ISCED level 3.4>,NaN,NaN,NaN,Yes,NaN,Yes,No,Yes,Yes,NaN
53835,<ISCED level 3.4>,<ISCED level 3.4>,No,No,No,No,NaN,No,No,No,No,NaN
53836,<ISCED level 3.4>,<ISCED level 3.4>,No,No,Yes,Yes,NaN,No,Yes,Yes,Yes,NaN
53837,NaN,<ISCED level 3.4>,Yes,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN
53838,<ISCED level 1>,<ISCED level 2>,No,No,No,Yes,NaN,No,No,No,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
456140,<ISCED level 3.4>,<ISCED level 3.4>,Yes,Yes,NaN,NaN,NaN,Yes,Yes,NaN,NaN,NaN
456141,<ISCED level 3.4>,<ISCED level 3.4>,No,Yes,No,NaN,NaN,NaN,Yes,NaN,NaN,NaN
456142,<ISCED level 2>,<ISCED level 3.4>,No,No,No,No,NaN,NaN,NaN,Yes,NaN,NaN
456143,<ISCED level 3.4>,<ISCED level 3.4>,No,No,Yes,No,NaN,No,No,Yes,No,NaN
456144,<ISCED level 3.4>,<ISCED level 3.4>,No,No,Yes,Yes,NaN,Yes,Yes,Yes,Yes,NaN

La variable *society*

Cette variable est associée à la classe sociale de la famille de l'élève. Cette variable à la fois en compte l'aspect financier mais également le niveau d'étude des parents ainsi que leurs qualifications et la position de leur métier au sein de la société. 

Cette variable prend ses valeurs de 0 à 10. 
0 : l'élève a du mal à s'intégrer, est rejeté
3 : l'élève sociabilise bien

In [43]:
society_liste=['ST259Q01JA']
df_society=data[society_liste].copy()
df_society

       ST259Q01JA
53834           5
53835           5
53836           7
53837           1
53838           8
...           ...
456140          9
456141         10
456142          7
456143         10
456144          6

[38674 rows x 1 columns]

La variable *social*

Cette variable prend en compte l'intégration sociale de l'élève notamment à l'école. Pour cela, on considère sa facilité à se faire des amis ou non, s'il est harcelé etc. 

Cette variable prend ses valeurs de 0 à 3. 
0 : l'élève a du mal à s'intégrer, est rejeté
3 : l'élève sociabilise bien

In [44]:
social_liste=['ST034Q0'+str(i)+'TA' for i in range(1,7)]+['ST038Q0' + str(i) +'NA' for i in range(3,9)]+['ST038Q09JA','ST038Q10JA','ST038Q11JA']
# les variables ST034Q1 - 4 -6 JA ainsi que les variables de ST038 contribuent négativement à social
df_social=data[social_liste].copy()
df_social

,ST034Q01TA,ST034Q02TA,ST034Q03TA,ST034Q04TA,ST034Q05TA,ST034Q06TA,ST038Q03NA,ST038Q04NA,ST038Q05NA,ST038Q06NA,ST038Q07NA,ST038Q08NA,ST038Q09JA,ST038Q10JA,ST038Q11JA
53834,NaN,Agree,Agree,Disagree,Agree,Strongly agree,A few times a year,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,A few times a month,Never or almost never
53835,Disagree,Agree,Agree,NaN,Disagree,Disagree,Never or almost never,A few times a year,Never or almost never,Never or almost never,Never or almost never,A few times a year,Never or almost never,A few times a year,Never or almost never
53836,Strongly disagree,Agree,NaN,Strongly disagree,Agree,Strongly disagree,Never or almost never,Never or almost never,Never or almost never,A few times a year,Never or almost never,Never or almost never,Never or almost never,A few times a year,Never or almost never
53837,Strongly disagree,Strongly disagree,Strongly disagree,NaN,Strongly disagree,Strongly disagree,Once a week or more,Once a week or more,Once a week or more,Once a week or more,A few times a month,A few times a month,Never or almost never,A few times a month,A few times a month
53838,NaN,Agree,Agree,Disagree,Agree,Disagree,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,A few times a year,Never or almost never
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456140,Disagree,Agree,NaN,Disagree,Agree,Disagree,Never or almost never,A few times a year,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never
456141,Strongly disagree,Disagree,NaN,Strongly disagree,Agree,Strongly disagree,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never
456142,NaN,Agree,Agree,Disagree,Agree,Disagree,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never
456143,Strongly disagree,Agree,Disagree,NaN,Agree,Strongly disagree,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never
456144,Agree,Disagree,NaN,Disagree,Disagree,Disagree,Never or almost never,A few times a year,NaN,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Once a week or more

La variable *safety*

Cette variable prend en compte la sécurité dans son environnement général, que ce soit à la maison, à l'école ou de façon générale à proximité de chez lui. 


Cette variable prend ses valeurs de 0 à 4.
0 : Tout va bien 
4 : Il est difficile d'aller à l'école en raison d'un cadré sécuritaire limité

In [45]:
safety_liste=['ST265Q0'+str(i)+'JA' for i in range(1,5)]+['ST266Q0'+str(i)+'JA' for i in range(1,6)]
# les variables de la deuxième liste contribuent négativement 
df_safety=data[safety_liste]
df_safety

,ST265Q01JA,ST265Q02JA,ST265Q03JA,ST265Q04JA,ST266Q01JA,ST266Q02JA,ST266Q03JA,ST266Q04JA,ST266Q05JA
53834,Agree,Disagree,Agree,Disagree,No,No,No,No,No
53835,Agree,Agree,Agree,Agree,No,No,No,No,No
53836,Strongly agree,Strongly agree,Agree,Strongly agree,No,No,No,No,No
53837,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Yes,NaN,Yes,Yes,Yes
53838,Agree,Disagree,Agree,Agree,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...
456140,Agree,Agree,Agree,Agree,Yes,Yes,Yes,Yes,Yes
456141,Strongly agree,Strongly agree,Strongly agree,Strongly agree,No,No,No,No,No
456142,Strongly agree,Strongly agree,Strongly agree,Strongly agree,No,No,No,No,No
456143,Agree,Agree,Agree,Agree,Yes,No,No,No,No
456144,Agree,Strongly agree,Strongly agree,Strongly agree,Yes,Yes,Yes,Yes,Yes

La variable *school*

Cette variable est associée à l'environnement au sein de l'école notamment les conditions de travail des élèves et d'enseignement pour les professeurs. Cette variable prend en compte l'agitation des élèves, leur capacité de concentration mais aussi l'état des salles de cours et des écoles. 

Cette variable prend ses valeurs de 0 à 5.

In [46]:
school_liste=['ST273Q0' + str(i) + 'JA' for i in range(1,8)]
df_school=data[school_liste]
df_school

,ST273Q01JA,ST273Q02JA,ST273Q03JA,ST273Q04JA,ST273Q05JA,ST273Q06JA,ST273Q07JA
53834,Every lesson,Every lesson,Every lesson,NaN,NaN,Every lesson,Every lesson
53835,Most lessons,NaN,Some lessons,Every lesson,Every lesson,NaN,Most lessons
53836,Some lessons,Never or almost never,NaN,Some lessons,Some lessons,NaN,Some lessons
53837,Every lesson,Every lesson,NaN,NaN,Every lesson,Every lesson,Every lesson
53838,NaN,Every lesson,NaN,Some lessons,Some lessons,Some lessons,Some lessons
...,...,...,...,...,...,...,...
456140,Never or almost never,Never or almost never,Never or almost never,Never or almost never,Never or almost never,NaN,NaN
456141,NaN,Most lessons,Some lessons,Never or almost never,Never or almost never,Never or almost never,NaN
456142,Never or almost never,NaN,Some lessons,Some lessons,NaN,Some lessons,Some lessons
456143,Some lessons,NaN,Some lessons,Some lessons,Some lessons,Some lessons,NaN
456144,Every lesson,NaN,Most lessons,Some lessons,Some lessons,NaN,Some lessons

La variable *teaching*

Cette variable est associé au niveau d'enseignement perçu par les élèves. Autrement dit, la qualité de l'enseignement reçu par l'élève selon sa perception (et donc sa satisfaction vis-à-vis des méthodes d'enseignement)

Cette variable prend ses valeurs de 0 à 4

In [47]:
teaching_liste=['ST272Q01JA']+['ST270Q0'+str(i)+'JA' for i in range(1,5)]
df_teaching=data[teaching_liste].copy()
df_teaching

,ST272Q01JA,ST270Q01JA,ST270Q02JA,ST270Q03JA,ST270Q04JA
53834,Best mathematics instruction possible10,Every lesson,Every lesson,Every lesson,Every lesson
53835,2,Never or almost never,Never or almost never,Never or almost never,Never or almost never
53836,8,Most lessons,Some lessons,Every lesson,Most lessons
53837,5,Every lesson,Every lesson,Every lesson,Every lesson
53838,6,Some lessons,Most lessons,Most lessons,Some lessons
...,...,...,...,...,...
456140,Best mathematics instruction possible10,Never or almost never,Never or almost never,Never or almost never,Never or almost never
456141,Best mathematics instruction possible10,Every lesson,Every lesson,Every lesson,Every lesson
456142,9,Every lesson,Most lessons,Most lessons,Most lessons
456143,Best mathematics instruction possible10,Some lessons,Some lessons,Some lessons,Some lessons
456144,7,Every lesson,Most lessons,Some lessons,Never or almost never

La variable *reasoning*

Cette variable est associé au niveau de tâches académiques qui nécessitent un certains raisonnement
mathématique par exemple. 


Cette variable prend ses valeurs de 0 à 4

In [48]:
reasoning_liste=['ST285Q0' + str(i) + 'JA' for i in range(1,10)]+['ST275Q0' + str(i) + 'WA' for i in range(1,10)]+['ST276Q0' + str(i) + 'JA' for i in range(1,10)]+['ST276Q10JA']
df_reasoning=data[reasoning_liste].copy()
df_reasoning

,ST285Q01JA,ST285Q02JA,ST285Q03JA,ST285Q04JA,ST285Q05JA,ST285Q06JA,ST285Q07JA,ST285Q08JA,ST285Q09JA,ST275Q01WA,...,ST276Q01JA,ST276Q02JA,ST276Q03JA,ST276Q04JA,ST276Q05JA,ST276Q06JA,ST276Q07JA,ST276Q08JA,ST276Q09JA,ST276Q10JA
53834,Less than half of the lessons,NaN,About half of the lessons,Less than half of the lessons,About half of the lessons,NaN,NaN,About half of the lessons,NaN,NaN,...,Sometimes,NaN,NaN,NaN,NaN,Frequently,Sometimes,Never,NaN,Rarely
53835,Never or almost never,NaN,More than half of the lessons,More than half of the lessons,More than half of the lessons,NaN,NaN,NaN,Never or almost never,Never,...,NaN,Frequently,Frequently,NaN,Never,NaN,Sometimes,NaN,Rarely,NaN
53836,NaN,About half of the lessons,NaN,About half of the lessons,NaN,About half of the lessons,About half of the lessons,NaN,About half of the lessons,NaN,...,Frequently,NaN,Sometimes,NaN,Sometimes,NaN,NaN,Frequently,NaN,Sometimes
53837,Never or almost never,NaN,Never or almost never,Never or almost never,NaN,Never or almost never,NaN,Never or almost never,NaN,NaN,...,NaN,Frequently,Frequently,NaN,Frequently,NaN,NaN,Frequently,Frequently,NaN
53838,Never or almost never,More than half of the lessons,NaN,NaN,More than half of the lessons,More than half of the lessons,More than half of the lessons,NaN,NaN,NaN,...,Frequently,NaN,NaN,NaN,NaN,NaN,Frequently,Frequently,Never,Never
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456140,Every lesson or almost every lesson,NaN,Every lesson or almost every lesson,NaN,Every lesson or almost every lesson,NaN,NaN,Every lesson or almost every lesson,Every lesson or almost every lesson,Never,...,NaN,NaN,Never,Never,Never,Never,Never,NaN,NaN,NaN
456141,NaN,More than half of the lessons,NaN,More than half of the lessons,More than half of the lessons,Never or almost never,NaN,More than half of the lessons,NaN,Never,...,NaN,Frequently,NaN,NaN,NaN,Frequently,NaN,Never,Never,Never
456142,Less than half of the lessons,Less than half of the lessons,NaN,NaN,NaN,Less than half of the lessons,Less than half of the lessons,Less than half of the lessons,NaN,NaN,...,NaN,Sometimes,Frequently,NaN,NaN,Frequently,NaN,Frequently,NaN,Frequently
456143,Less than half of the lessons,NaN,NaN,NaN,Never or almost never,Never or almost never,More than half of the lessons,NaN,About half of the lessons,Rarely,...,Sometimes,Sometimes,Sometimes,Sometimes,Sometimes,NaN,NaN,NaN,NaN,NaN
456144,Never or almost never,Less than half of the lessons,Less than half of the lessons,Less than half of the lessons,NaN,NaN,About half of the lessons,NaN,NaN,NaN,...,NaN,NaN,Frequently,NaN,Frequently,NaN,NaN,Frequently,Frequently,Frequently

La variable *family_support*

Cette variable mesure l'accompagnement de l'élève par sa famille. Autrement dit, elle permet de savoir si l'élève est soutenu ou non dans sa scolarité mais aussi de façon générale lors de périodes difficiles par sa famille.

Cette variable prend ses valeurs de 0 à 4

In [49]:
family_support_liste=['ST300Q0' + str(i) + 'JA' for i in range(1,10)]+['ST300Q10JA']
df_family_support=data[family_support_liste]
df_family_support

,ST300Q01JA,ST300Q02JA,ST300Q03JA,ST300Q04JA,ST300Q05JA,ST300Q06JA,ST300Q07JA,ST300Q08JA,ST300Q09JA,ST300Q10JA
53834,About once or twice a month,About once or twice a month,About once or twice a month,NaN,NaN,NaN,About once or twice a month,NaN,About once or twice a month,NaN
53835,Never or almost never,NaN,Every day or almost every day,NaN,NaN,Never or almost never,Every day or almost every day,NaN,Never or almost never,NaN
53836,NaN,About once or twice a month,About once or twice a year,NaN,About once or twice a year,About once or twice a year,NaN,NaN,About once or twice a week,NaN
53837,Every day or almost every day,Every day or almost every day,Every day or almost every day,NaN,NaN,NaN,Every day or almost every day,Every day or almost every day,NaN,NaN
53838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Every day or almost every day
...,...,...,...,...,...,...,...,...,...,...
456140,Every day or almost every day,Every day or almost every day,NaN,Every day or almost every day,NaN,NaN,NaN,Every day or almost every day,Every day or almost every day,NaN
456141,Every day or almost every day,NaN,NaN,Every day or almost every day,Every day or almost every day,NaN,Every day or almost every day,Every day or almost every day,NaN,NaN
456142,About once or twice a year,NaN,NaN,About once or twice a year,NaN,NaN,About once or twice a week,About once or twice a week,NaN,Every day or almost every day
456143,About once or twice a month,NaN,About once or twice a month,NaN,NaN,About once or twice a month,NaN,About once or twice a month,About once or twice a month,NaN
456144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

La variable *school_support*

Cette variable mesure l'accompagnement de l'élève par l'école. Autrement dit, elle permet de savoir si l'élève est soutenu ou non dans sa scolarité mais aussi de façon générale lors de périodes difficiles par les équipes pédagogiques.  

Cette variable prend ses valeurs de 0 à 4

In [50]:
school_support_liste=['ST267Q0' + str(i) + 'JA' for i in range(1,9)]+['ST354Q03JA','ST354Q08JA']+['ST348Q0' + str(i) + 'JA' for i in range(1,9)]
# Les variables ST267Q04JA et ST267Q08JA contribuent négativement à school_support
df_school_support=data[school_support_liste].copy()
df_school_support

,ST267Q01JA,ST267Q02JA,ST267Q03JA,ST267Q04JA,ST267Q05JA,ST267Q06JA,ST267Q07JA,ST267Q08JA,ST354Q03JA,ST354Q08JA,ST348Q01JA,ST348Q02JA,ST348Q03JA,ST348Q04JA,ST348Q05JA,ST348Q06JA,ST348Q07JA,ST348Q08JA
53834,NaN,NaN,NaN,Agree,Strongly agree,Agree,Strongly agree,Strongly disagree,NaN,Agree,Never,NaN,NaN,NaN,Never,Never,Never,Never
53835,NaN,NaN,Agree,Agree,Disagree,NaN,Disagree,Disagree,NaN,NaN,A few times,Every day or almost every day,NaN,A few times,Never,A few times,NaN,NaN
53836,Agree,Strongly disagree,Agree,NaN,Disagree,NaN,Strongly disagree,NaN,Disagree,Disagree,A few times,Every day or almost every day,Every day or almost every day,NaN,Never,Every day or almost every day,NaN,NaN
53837,Strongly agree,NaN,NaN,Strongly agree,NaN,Strongly agree,Strongly agree,Strongly agree,NaN,Agree,A few times,A few times,A few times,NaN,Every day or almost every day,Every day or almost every day,NaN,NaN
53838,NaN,Agree,Disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Every day or almost every day,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456140,NaN,Disagree,Agree,Disagree,NaN,Agree,Disagree,NaN,Strongly agree,NaN,NaN,NaN,Every day or almost every day,Every day or almost every day,Every day or almost every day,Every day or almost every day,NaN,Every day or almost every day
456141,Strongly agree,NaN,NaN,Strongly agree,Agree,Strongly agree,Strongly agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456142,NaN,NaN,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,NaN,Strongly disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456143,Agree,NaN,Agree,NaN,Agree,NaN,Agree,Agree,NaN,NaN,Never,NaN,NaN,Never,Never,Never,NaN,Never
456144,Agree,Agree,Agree,Agree,NaN,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
list(s[s.str.startswith("ST250")])

['ST250Q01JA',
 'ST250Q02JA',
 'ST250Q03JA',
 'ST250Q04JA',
 'ST250Q05JA',
 'ST250D06JA',
 'ST250D07JA']

#### **Variables du PA questionnaire**

#### **Variables du CREAT questionnaire**